{
 "title": "Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "query": "{\"find\": \"terms\", \"field\": \"path.keyword\", \"type\": \"disk\"}"
   },
   {
    "name": "host",
    "query": "{\"find\": \"terms\", \"field\": \"host.keyword\", \"type\": \"disk\"}"
   },
   {
    "name": "disk",
    "query": "{\"find\": \"terms\", \"field\": \"device.keyword\", \"type\": \"disk\"}"
   },
   {
    "name": "container",
    "query": "{\"find\": \"terms\", \"field\": \"name.keyword\", \"type\": \"containers\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Apps",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "container.keyword",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "proc_name.keyword",
       "id": "10",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pid",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "running_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "create_time",
       "id": "12",
       "inlineScript": "_value * 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value * 1000" } },
       "type": "min"
      }
     ],
     "query": "_type:app AND host:$host AND container:$container",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{host}}-cpu_perc",
     "bucketAggs": [
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu_perc",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:sysload AND host:$host",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-mem_perc",
     "bucketAggs": [
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mem_perc",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:sysload AND host:$host",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-mem_avail",
     "bucketAggs": [
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mem_avail",
       "id": "1",
       "inlineScript": "_value / 1024 / 1024",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1024 / 1024" } },
       "type": "avg"
      }
     ],
     "query": "_type:sysload AND host:$host",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-mem_used",
     "bucketAggs": [
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mem_used",
       "id": "1",
       "inlineScript": "_value / 1024 / 1024",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1024 / 1024" } },
       "type": "avg"
      }
     ],
     "query": "_type:sysload AND host:$host",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Containers I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{host}}-{{name}}-net_input",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "net_input",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:containers AND host:$host AND name:$container",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-{{name}}-net_output",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "net_output",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:containers AND host:$host AND name:$container",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-{{name}}-block_read",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "block_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:containers AND host:$host AND name:$container",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-{{name}}-block_write",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "block_write",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:containers AND host:$host AND name:$container",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Containers Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{host}}-{{name}}-cpu_perc",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu_perc",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:containers AND name:$container AND host:$host",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-{{name}}-mem_perc",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mem_perc",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:containers AND name:$container AND host:$host",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-{{name}}-mem_used",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mem_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:containers AND name:$container AND host:$host",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{host}}-gpu{{gpu_id}}-gpu_perc",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "20s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gpu_perc",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:gpu AND host:$host",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-gpu{{gpu_id}}-mem_perc",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "20s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mem_perc",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:gpu AND host:$host",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-gpu{{gpu_id}}-mem_free",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "20s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mem_free",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:gpu AND host:$host",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-gpu{{gpu_id}}-mem_used",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "20s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mem_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:gpu AND host:$host",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{host}}-{{path.keyword}}-percent",
     "bucketAggs": [
      {
       "fake": true,
       "field": "path.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "path.keyword:$path AND host:$host",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-{{path.keyword}}-used",
     "bucketAggs": [
      {
       "fake": true,
       "field": "path.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "path.keyword:$path AND host:$host",
     "timeField": "timestamp"
    },
    {
     "alias": "{{host}}-{{path.keyword}}-free",
     "bucketAggs": [
      {
       "fake": true,
       "field": "path.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "free",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "path.keyword:$path AND host:$host",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "{{host}}-gpu{{gpu_id}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "20s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gpu_temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:gpu AND host:$host",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}